#!/usr/local/bin/python

import os
import sys
import traceback
import urllib2

import json

orchids = [
    "Arpophyllum giganteum",
    "Beloglottis costaricensis",
    "Bletia purpurea",
    "Brassavola acaulis",
    "Brassavola cucullata",
    "Brassavola nodosa",
    "Brassavola nodosa var. grandiflora",
    "Brassia caudata",
    "Brassia maculata",
    "Bulbophyllum aristatum",
    "Bulbophyllum oerstedii",
    "Campylocentrum fasciola",
    "Campylocentrum hondurense",
    "Campylocentrum micranthum",
    "Campylocentrum poeipegii",
    "Campylocentrum schiedei",
    "Catasetum integerrimum",
    "Cattleya bowringiana",
    "Caularthron bilamellatum",
    "Chysis bractescens",
    "Clowesia russelliana",
    "Cochleanthes flabelliformis",
    "Coelia bella",
    "Comparettia falcata",
    "Coryanthes speciosa",
    "Corymborkis forcipigera",
    "Cranichis muscosa",
    "Cryptarrhena guatemalensis",
    "Cryptarrhena lunata",
    "Cyclopogon sp",
    "Cyclopogon comosus",
    "Cyclopogon cranichoides",
    "Cyclopogon elatus",
    "Cyclopogon prasophyllum",
    "Cycnoches egertonianum",
    "Cycnoches ventricosum",
    "Cyrtopodium punctatum",
    "Dichaea brachypoda",
    "Dichaea glauca",
    "Dichaea graminoides",
    "Dichaea hystracina",
    "Dichaea muricata var. neglecta",
    "Dichaea muricatoides",
    "Dichaea panamensis",
    "Dichaea trulla",
    "Dichaea tuerckheimii",
    "Dimerandra emarginata",
    "Dresslerella powellii",
    "Dryadella linearifolia",
    "Elleanthus caricoides",
    "Elleanthus cynarocephalus",
    "Elleanthus linifolius",
    "Encyclia adenocarpon",
    "Encyclia alata",
    "Encyclia amanda",
    "Encyclia ambigua",
    "Encyclia asperula",
    "Encyclia baculus",
    "Encyclia belizensis subsp. belizensis",
    "Encyclia boothiana subsp. boothiana",
    "Encyclia bractescens",
    "Encyclia chacaoensis",
    "Encyclia chloroleuca",
    "Encyclia cochleata",
    "Encyclia cordigera",
    "Encyclia crassilabia",
    "Encyclia dickinsoniana",
    "Encyclia distantiflora",
    "Encyclia guatemalensis",
    "Encyclia livida",
    "Encyclia michuacana",
    "Encyclia neurosa",
    "Encyclia polybulbon",
    "Encyclia porrecta",
    "Encyclia pygmaea",
    "Encyclia radiata",
    "Epidanthus paranthicus",
    "Epidendrum acunae",
    "Epidendrum ciliare",
    "Epidendrum clowesii",
    "Epidendrum cristatum",
    "Epidendrum cystosum",
    "Epidendrum densiflorum",
    "Epidendrum difforme",
    "Epidendrum diffusum",
    "Epidendrum hawkesii",
    "Epidendrum imatophyllum",
    "Epidendrum isomerum",
    "Epidendrum macroclinium",
    "Epidendrum nitens",
    "Epidendrum nocturnum",
    "Epidendrum paniculatum",
    "Epidendrum polyanthum",
    "Epidendrum ramosum",
    "Epidendrum rigidum",
    "Epidendrum scriptum",
    "Epidendrum sculptum",
    "Epidendrum secundum",
    "Epidendrum stamfordianum",
    "Epidendrum strobiliferum",
    "Episthephium ellipticum",
    "Eriopsis biloba",
    "Erythrodes purpurea",
    "Eulophia alta",
    "Eurystyles borealis",
    "Galeandra batemanii",
    "Gongora cassidea",
    "Gongora quinquenervis",
    "Gongora truncata",
    "Gongora unicolor",
    "Goodyera erosa",
    "Habenaria brownelliana",
    "Habenaria clypeata",
    "Habenaria distans",
    "Habenaria entomantha",
    "Habenaria floribunda",
    "Habenaria lankesteri",
    "Habenaria mesodactyla",
    "Habenaria monorrhiza",
    "Habenaria novemfida",
    "Habenaria quinqueseta",
    "Habenaria repens",
    "Habenaria rodeiensis",
    "Habenaria trifida",
    "Huntleya fasciata",
    "Ionopsis satyrioides",
    "Ionopsis utricularioides",
    "Isochilus carnosiflorus",
    "Jacquiniella equitantifolia",
    "Jacquiniella globosa",
    "Jacquiniella teretifolia",
    "Kegeliella atropilosa",
    "Koellensteinia tricolor",
    "Lacaena bicolor",
    "Laelia inconspicua",
    "Leochilus labiatus",
    "Lepanthes acuminata",
    "Lepanthes arachnion",
    "Lepanthes disticha",
    "Lepanthes inaequalis",
    "Lepanthes johnsonii",
    "Lepanthes turialvae",
    "Lepanthopsis floripecten",
    "Leucohyle subulata",
    "Liparis elata",
    "Liparis nervosa",
    "Lockhartia hercodonta",
    "Lockhartia pittieri",
    "Lycaste aromatica",
    "Lycaste cochleata",
    "Lycaste leucantha",
    "Lycaste tricolor",
    "Lyroglossa pubicaulis",
    "Macradenia brassavolae",
    "Macroclinium paniculata",
    "Malaxis histionantha",
    "Masdevallia adamsii",
    "Masdevallia floribunda",
    "Masdevallia tubuliflora",
    "Maxillaria aciantha",
    "Maxillaria alba",
    "Maxillaria amparoana",
    "Maxillaria brunnea",
    "Maxillaria cobanensis",
    "Maxillaria conferta",
    "Maxillaria confusa",
    "Maxillaria crassifolia",
    "Maxillaria cucullata",
    "Maxillaria densa",
    "Maxillaria discolor",
    "Maxillaria elatior",
    "Maxillaria friedrichsthalii",
    "Maxillaria fulgens",
    "Maxillaria hedwigae",
    "Maxillaria pulchra",
    "Maxillaria ringens",
    "Maxillaria rufescens",
    "Maxillaria tenuifolia",
    "Maxillaria uncata",
    "Maxillaria variabilis",
    "Mesadenella petenensis",
    "Mesadenella polyanthus",
    "Mormodes buccinator",
    "Mormodes warscewiczii",
    "Mormolyca ringens",
    "Myoxanthus octomerioides",
    "Myrmecophila brysiana",
    "Myrmecophila tibicinis",
    "Myrmecophila wendlandii",
    "Nidema boothii",
    "Notylia barkeri",
    "Notylia wullschlaegeliana",
    "Octomeria graminifolia",
    "Oerstedella verrucosa",
    "Oncidium altissimum",
    "Oncidium ascendens",
    "Oncidium carthagenense",
    "Oncidium cebolleta",
    "Oncidium ensatum",
    "Oncidium lindenii",
    "Oncidium sphacelatum",
    "Oncidium stipitatum",
    "Oncidium subcruciforme",
    "Ornithocephalus bicornis",
    "Ornithocephalus gladiatus",
    "Pelexia callifera",
    "Pelexia adnata",
    "Pelexia congesta",
    "Pelexia funckiana",
    "Pelexia olivacea",
    "Pelexia richardiana",
    "Platystele compacta",
    "Platystele minimiflora",
    "Platystele ovatilabia",
    "Platystele oxyglossa",
    "Platystele pedicellaris",
    "Platystele repens",
    "Platystele stenostachya",
    "Platythelys maculata",
    "Platythelys querceticola",
    "Pleurothallis abjecta",
    "Pleurothallis angustifolia",
    "Pleurothallis angustisepala",
    "Pleurothallis barboselloides",
    "Pleurothallis barbulata",
    "Pleurothallis brighamii",
    "Pleurothallis cardiothallis",
    "Pleurothallis cobanensis",
    "Pleurothallis convallaria",
    "Pleurothallis deregularis",
    "Pleurothallis duplooyi",
    "Pleurothallis erinacea",
    "Pleurothallis gelida",
    "Pleurothallis glandulosa",
    "Pleurothallis grobyi",
    "Pleurothallis hastata",
    "Pleurothallis homolantha",
    "Pleurothallis hondurensis",
    "Pleurothallis johnsonii",
    "Pleurothallis lewisae",
    "Pleurothallis matudiana",
    "Pleurothallis microphylla",
    "Pleurothallis pansamalae",
    "Pleurothallis peperomioides",
    "Pleurothallis quadrifida",
    "Pleurothallis sertularioides",
    "Pleurothallis setosa",
    "Pleurothallis spectrilinguis",
    "Pleurothallis tikalensis",
    "Pleurothallis tribuloides",
    "Pleurothallis tuerckheimii",
    "Pleurothallis uncinata",
    "Pleurothallis yucatanensis",
    "Polystachya clavata",
    "Polystachya foliosa",
    "Polystachya masayensis",
    "Ponera striata",
    "Prescottia oligantha",
    "Prescottia stachyodes",
    "Pseudogoodyera wrightii",
    "Psilochilus macrophyllus",
    "Psygmorchis pusilla",
    "Restrepiella ophiocephala",
    "Rhyncholaelia digbyana",
    "Rhyncholaelia glauca",
    "Sacoila lanceolata",
    "Sarcoglottis rosulata",
    "Sarcoglottis sceptrodes",
    "Scaphosepalum microdactylum",
    "Scaphyglottis behrii",
    "Scaphyglottis confusa",
    "Scaphyglottis fasciculata",
    "Scaphyglottis leucantha",
    "Scaphyglottis lindeniana",
    "Scaphyglottis longicaulis",
    "Scaphyglottis minutiflora",
    "Scaphyglottis prolifera",
    "Sobralia decora",
    "Sobralia fragrans",
    "Sobralia macrantha",
    "Sobralia mucronata",
    "Spiranthes torta",
    "Stanhopea ecornuta",
    "Stanhopea graveolens",
    "Stanhopea inodora",
    "Stanhopea oculata",
    "Stelis bidentata",
    "Stelis ciliaris",
    "Stelis gracilis",
    "Stelis microchila",
    "Stelis oxypetala",
    "Stelis purpurascens",
    "Stelis rubens",
    "Teuscheria pickiana",
    "Trichopilia tortilis",
    "Trichosalpinx blaisdellii",
    "Trichosalpinx ciliaris",
    "Trichosalpinx foliata",
    "Trigonidium egertonianum",
    "Vanilla hartii",
    "Vanilla pfaviana",
    "Vanilla planifolia",
    "Xylobium colleyi"]

base_url = 'http://belizebotanic.org/gallery/index.php/rest/'
api_key = open(os.path.join(os.getcwd(), 'gallery_api.key')).read()

def get_gallery_url(url):
    request = urllib2.Request(url)
    request.add_header('X-Gallery-Request-Key', api_key)
    request.add_header('X-Gallery-Request-Method', 'get')
    return urllib2.urlopen(request)

print "Content-Type: text/html\n\n"

# get all the tags ids
tagged = {}
start = 0
while True:
    try:
        response = get_gallery_url(base_url + 'tags?num=100&start=%s' % start)
        start = start+100
    except Exception, e:
        print 'Error: '
        print e
        print traceback.format_exc()
        sys.exit(1)

    # find all the tags that match orchid names by querying the tag ids
    members = json.load(response)['members']
    if len(members) == 0:
        break
    for i in members:
        try:
            response = get_gallery_url(i)
        except urllib2.URLError, e:
            print e
            print '** ERROR: Could not open URL: %s' % i
            response = None

        if response is None:
            continue
        entity = json.load(response)['entity']
        if entity['name'] in orchids:
            tagged[entity['name']] = entity

# create a span for each of the orchids and include links for each
# name with a matching tag to the orchid page
orchid_url = 'http://belizebotanic.org/orchid?'
tagged_keys = tagged.keys()
for orchid in orchids:
    if orchid in tagged_keys:
        span = '<span><a href="' + orchid_url + '=%(name)s&orchid_id=%(id)s">%(name)s</a></span>'
        print span % tagged[orchid]
    else:
        print '<span>%s</span>' % orchid
